image: node:latest

cache:
  paths:
    - $CI_PROJECT_DIR/Super\ Sigma\ App/node_modules/

before_script:
  - cd $CI_PROJECT_DIR/Super\ Sigma\ App
  - npm install

validate:
  stage: .pre
  script:
    - npm run lint
    - npm run type-check

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm install
    - npm run test